-- Baseline schema khớp entity hiện tại (Hibernate trên H2).
-- Database đã có bảng (ddl-auto=update trước đây) được Flyway baseline ở version 1, không chạy file này.

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  role ENUM('USER', 'ADMIN') NOT NULL,
  native_language VARCHAR(255),
  target_level ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2'),
  study_goal_min INTEGER NOT NULL,
  last_active_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE vocab_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  icon VARCHAR(255),
  sort_order INTEGER NOT NULL,
  CONSTRAINT uk_vocab_topics_name UNIQUE (name)
);

CREATE TABLE vocabulary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word VARCHAR(255) NOT NULL,
  phonetic VARCHAR(255),
  meaning_vi VARCHAR(255) NOT NULL,
  meaning_en VARCHAR(255),
  part_of_speech ENUM(
    'noun', 'verb', 'adjective', 'adverb', 'preposition', 'conjunction',
    'pronoun', 'interjection', 'phrase', 'phrasal_verb'
  ),
  level ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2') NOT NULL,
  example_en VARCHAR(255),
  example_vi VARCHAR(255),
  audio_url VARCHAR(255),
  image_url VARCHAR(255),
  frequency_rank INTEGER,
  sort_order INTEGER NOT NULL,
  topic_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_vocabulary_topic FOREIGN KEY (topic_id) REFERENCES vocab_topics (id)
);

CREATE TABLE srs_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  content_type ENUM('VOCABULARY', 'GRAMMAR') NOT NULL,
  content_id BIGINT NOT NULL,
  ease_factor DOUBLE PRECISION NOT NULL,
  interval_days INTEGER NOT NULL,
  repetitions INTEGER NOT NULL,
  next_review_at TIMESTAMP WITH TIME ZONE,
  last_review_at TIMESTAMP WITH TIME ZONE,
  correct_count INTEGER NOT NULL,
  wrong_count INTEGER NOT NULL,
  review_streak INTEGER NOT NULL,
  mastered BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uk_srs_cards_user_content UNIQUE (user_id, content_type, content_id)
);

CREATE TABLE grammar_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  level ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2') NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE grammar_lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  explanation CLOB NOT NULL,
  level ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2') NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_grammar_lessons_topic FOREIGN KEY (topic_id) REFERENCES grammar_topics (id)
);

CREATE TABLE grammar_examples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id BIGINT NOT NULL,
  en VARCHAR(255) NOT NULL,
  vi VARCHAR(255),
  audio_url VARCHAR(255),
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_grammar_examples_lesson FOREIGN KEY (lesson_id) REFERENCES grammar_lessons (id)
);

CREATE TABLE grammar_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id BIGINT NOT NULL,
  question VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  explanation VARCHAR(255),
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_grammar_exercises_lesson FOREIGN KEY (lesson_id) REFERENCES grammar_lessons (id)
);

CREATE TABLE grammar_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise_id BIGINT NOT NULL,
  text VARCHAR(255) NOT NULL,
  correct BOOLEAN NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_grammar_options_exercise FOREIGN KEY (exercise_id) REFERENCES grammar_exercises (id)
);

CREATE TABLE reading_passages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content CLOB NOT NULL,
  level ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2') NOT NULL,
  source VARCHAR(255),
  estimated_min INTEGER NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE reading_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage_id BIGINT NOT NULL,
  question VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  explanation VARCHAR(255),
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_reading_questions_passage FOREIGN KEY (passage_id) REFERENCES reading_passages (id)
);

CREATE TABLE reading_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL,
  text VARCHAR(255) NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_reading_options_question FOREIGN KEY (question_id) REFERENCES reading_questions (id)
);

CREATE TABLE reading_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  passage_id BIGINT NOT NULL,
  correct_count INTEGER NOT NULL,
  total INTEGER NOT NULL,
  percent DOUBLE PRECISION NOT NULL,
  submitted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE listening_tracks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  youtube_url VARCHAR(255),
  audio_url VARCHAR(255),
  transcript CLOB,
  level ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2') NOT NULL,
  duration_sec INTEGER,
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE listening_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id BIGINT NOT NULL,
  question VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  explanation VARCHAR(255),
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_listening_questions_track FOREIGN KEY (track_id) REFERENCES listening_tracks (id)
);

CREATE TABLE listening_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL,
  text VARCHAR(255) NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_listening_options_question FOREIGN KEY (question_id) REFERENCES listening_questions (id)
);

CREATE TABLE listening_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  track_id BIGINT NOT NULL,
  correct_count INTEGER NOT NULL,
  total INTEGER NOT NULL,
  percent DOUBLE PRECISION NOT NULL,
  submitted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE dictation_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  vocab_id BIGINT NOT NULL,
  user_input VARCHAR(255) NOT NULL,
  correct BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE study_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  study_date DATE NOT NULL,
  seconds INTEGER NOT NULL,
  cards_studied INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uk_study_sessions_user_date UNIQUE (user_id, study_date)
);
