-- Schema IELTS: hồ sơ, band, ngân hàng câu hỏi dùng chung, Writing, Speaking, bài thi, lộ trình.
-- Chạy được trên Postgres và H2 (MODE=PostgreSQL). Văn bản dài dùng VARCHAR không độ dài (xem V2).
-- Band lưu DOUBLE PRECISION: mọi giá trị là bội của 0.5 nên biểu diễn chính xác.

-- 1. Hồ sơ và band ------------------------------------------------------------

CREATE TABLE ielts_profiles (
  user_id BIGINT PRIMARY KEY,
  module VARCHAR(20) NOT NULL,
  current_band DOUBLE PRECISION,
  target_band DOUBLE PRECISION NOT NULL,
  exam_date DATE,
  daily_minutes INTEGER NOT NULL,
  study_days_per_week INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_ielts_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE band_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  skill VARCHAR(20) NOT NULL,
  band DOUBLE PRECISION NOT NULL,
  source VARCHAR(20) NOT NULL,
  source_ref_id BIGINT,
  recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_band_records_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_band_records_user_skill ON band_records (user_id, skill, recorded_at);

-- Bảng quy đổi điểm thô /40 sang band. Để trong DB vì bảng chính thức có thể lệch nhẹ giữa các đề.
CREATE TABLE band_conversions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill VARCHAR(20) NOT NULL,
  module VARCHAR(20) NOT NULL,
  raw_min INTEGER NOT NULL,
  raw_max INTEGER NOT NULL,
  band DOUBLE PRECISION NOT NULL
);

INSERT INTO band_conversions (skill, module, raw_min, raw_max, band) VALUES
  ('LISTENING', 'BOTH', 39, 40, 9.0), ('LISTENING', 'BOTH', 37, 38, 8.5), ('LISTENING', 'BOTH', 35, 36, 8.0),
  ('LISTENING', 'BOTH', 32, 34, 7.5), ('LISTENING', 'BOTH', 30, 31, 7.0), ('LISTENING', 'BOTH', 26, 29, 6.5),
  ('LISTENING', 'BOTH', 23, 25, 6.0), ('LISTENING', 'BOTH', 18, 22, 5.5), ('LISTENING', 'BOTH', 16, 17, 5.0),
  ('LISTENING', 'BOTH', 13, 15, 4.5), ('LISTENING', 'BOTH', 10, 12, 4.0), ('LISTENING', 'BOTH', 8, 9, 3.5),
  ('LISTENING', 'BOTH', 6, 7, 3.0), ('LISTENING', 'BOTH', 4, 5, 2.5), ('LISTENING', 'BOTH', 1, 3, 2.0),
  ('LISTENING', 'BOTH', 0, 0, 0.0),
  ('READING', 'ACADEMIC', 39, 40, 9.0), ('READING', 'ACADEMIC', 37, 38, 8.5), ('READING', 'ACADEMIC', 35, 36, 8.0),
  ('READING', 'ACADEMIC', 33, 34, 7.5), ('READING', 'ACADEMIC', 30, 32, 7.0), ('READING', 'ACADEMIC', 27, 29, 6.5),
  ('READING', 'ACADEMIC', 23, 26, 6.0), ('READING', 'ACADEMIC', 19, 22, 5.5), ('READING', 'ACADEMIC', 15, 18, 5.0),
  ('READING', 'ACADEMIC', 13, 14, 4.5), ('READING', 'ACADEMIC', 10, 12, 4.0), ('READING', 'ACADEMIC', 8, 9, 3.5),
  ('READING', 'ACADEMIC', 6, 7, 3.0), ('READING', 'ACADEMIC', 4, 5, 2.5), ('READING', 'ACADEMIC', 1, 3, 2.0),
  ('READING', 'ACADEMIC', 0, 0, 0.0),
  ('READING', 'GENERAL', 40, 40, 9.0), ('READING', 'GENERAL', 39, 39, 8.5), ('READING', 'GENERAL', 37, 38, 8.0),
  ('READING', 'GENERAL', 36, 36, 7.5), ('READING', 'GENERAL', 34, 35, 7.0), ('READING', 'GENERAL', 32, 33, 6.5),
  ('READING', 'GENERAL', 30, 31, 6.0), ('READING', 'GENERAL', 27, 29, 5.5), ('READING', 'GENERAL', 23, 26, 5.0),
  ('READING', 'GENERAL', 19, 22, 4.5), ('READING', 'GENERAL', 15, 18, 4.0), ('READING', 'GENERAL', 12, 14, 3.5),
  ('READING', 'GENERAL', 9, 11, 3.0), ('READING', 'GENERAL', 6, 8, 2.5), ('READING', 'GENERAL', 1, 5, 2.0),
  ('READING', 'GENERAL', 0, 0, 0.0);

-- 2. Nội dung đọc/nghe thêm thông tin IELTS -------------------------------------

ALTER TABLE reading_passages ADD COLUMN module VARCHAR(20) DEFAULT 'BOTH' NOT NULL;
ALTER TABLE reading_passages ADD COLUMN topic VARCHAR(255);
ALTER TABLE reading_passages ADD COLUMN band_min DOUBLE PRECISION;
ALTER TABLE reading_passages ADD COLUMN band_max DOUBLE PRECISION;
ALTER TABLE reading_passages ADD COLUMN license VARCHAR(100);

ALTER TABLE listening_tracks ADD COLUMN ielts_part INTEGER;
ALTER TABLE listening_tracks ADD COLUMN band_min DOUBLE PRECISION;
ALTER TABLE listening_tracks ADD COLUMN band_max DOUBLE PRECISION;
ALTER TABLE listening_tracks ADD COLUMN source VARCHAR(255);
ALTER TABLE listening_tracks ADD COLUMN license VARCHAR(100);

-- 3. Ngân hàng câu hỏi dùng chung cho Reading và Listening ----------------------

CREATE TABLE question_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_type VARCHAR(30) NOT NULL,
  owner_id BIGINT NOT NULL,
  question_type VARCHAR(40) NOT NULL,
  instruction VARCHAR NOT NULL,
  word_limit INTEGER,
  image_url VARCHAR(500),
  sort_order INTEGER NOT NULL
);
CREATE INDEX ix_question_groups_owner ON question_groups (owner_type, owner_id);

-- Lựa chọn dùng chung cả nhóm: danh sách heading, sentence ending, feature...
CREATE TABLE question_group_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  option_key VARCHAR(10) NOT NULL,
  text VARCHAR NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_question_group_options_group FOREIGN KEY (group_id) REFERENCES question_groups (id)
);

CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  number INTEGER NOT NULL,
  prompt VARCHAR NOT NULL,
  -- Mảng JSON các đáp án được chấp nhận, ví dụ ["1990","nineteen ninety"] hoặc ["B"].
  accepted_answers VARCHAR NOT NULL,
  explanation VARCHAR,
  evidence VARCHAR,
  legacy_id BIGINT,
  CONSTRAINT fk_questions_group FOREIGN KEY (group_id) REFERENCES question_groups (id)
);
CREATE INDEX ix_questions_group ON questions (group_id);

-- Lựa chọn riêng của từng câu (trắc nghiệm).
CREATE TABLE question_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL,
  option_key VARCHAR(10) NOT NULL,
  text VARCHAR NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_question_options_question FOREIGN KEY (question_id) REFERENCES questions (id)
);

-- 4. Chuyển câu hỏi trắc nghiệm cũ sang bảng mới ---------------------------------
-- Mỗi bài cũ thành một nhóm MULTIPLE_CHOICE. Đáp án cũ lưu nguyên văn lựa chọn; bảng mới lưu chữ cái A, B, C...

INSERT INTO question_groups (owner_type, owner_id, question_type, instruction, sort_order)
SELECT DISTINCT 'READING_PASSAGE', passage_id, 'MULTIPLE_CHOICE', 'Choose the correct letter, A, B, C or D.', 1
FROM reading_questions;

INSERT INTO question_groups (owner_type, owner_id, question_type, instruction, sort_order)
SELECT DISTINCT 'LISTENING_TRACK', track_id, 'MULTIPLE_CHOICE', 'Choose the correct letter, A, B, C or D.', 1
FROM listening_questions;

INSERT INTO questions (group_id, number, prompt, accepted_answers, explanation, legacy_id)
SELECT g.id,
       ROW_NUMBER() OVER (PARTITION BY q.passage_id ORDER BY q.sort_order, q.id),
       q.question,
       '["' || COALESCE((
         SELECT CASE o.sort_order WHEN 1 THEN 'A' WHEN 2 THEN 'B' WHEN 3 THEN 'C' WHEN 4 THEN 'D'
                                  WHEN 5 THEN 'E' WHEN 6 THEN 'F' ELSE 'G' END
         FROM reading_options o
         WHERE o.question_id = q.id AND o.text = q.answer
         ORDER BY o.sort_order FETCH FIRST 1 ROWS ONLY), 'A') || '"]',
       q.explanation,
       q.id
FROM reading_questions q
JOIN question_groups g ON g.owner_type = 'READING_PASSAGE' AND g.owner_id = q.passage_id;

INSERT INTO question_options (question_id, option_key, text, sort_order)
SELECT nq.id,
       CASE o.sort_order WHEN 1 THEN 'A' WHEN 2 THEN 'B' WHEN 3 THEN 'C' WHEN 4 THEN 'D'
                         WHEN 5 THEN 'E' WHEN 6 THEN 'F' ELSE 'G' END,
       o.text,
       o.sort_order
FROM reading_options o
JOIN questions nq ON nq.legacy_id = o.question_id
JOIN question_groups g ON g.id = nq.group_id AND g.owner_type = 'READING_PASSAGE';

UPDATE questions SET legacy_id = NULL;

INSERT INTO questions (group_id, number, prompt, accepted_answers, explanation, legacy_id)
SELECT g.id,
       ROW_NUMBER() OVER (PARTITION BY q.track_id ORDER BY q.sort_order, q.id),
       q.question,
       '["' || COALESCE((
         SELECT CASE o.sort_order WHEN 1 THEN 'A' WHEN 2 THEN 'B' WHEN 3 THEN 'C' WHEN 4 THEN 'D'
                                  WHEN 5 THEN 'E' WHEN 6 THEN 'F' ELSE 'G' END
         FROM listening_options o
         WHERE o.question_id = q.id AND o.text = q.answer
         ORDER BY o.sort_order FETCH FIRST 1 ROWS ONLY), 'A') || '"]',
       q.explanation,
       q.id
FROM listening_questions q
JOIN question_groups g ON g.owner_type = 'LISTENING_TRACK' AND g.owner_id = q.track_id;

INSERT INTO question_options (question_id, option_key, text, sort_order)
SELECT nq.id,
       CASE o.sort_order WHEN 1 THEN 'A' WHEN 2 THEN 'B' WHEN 3 THEN 'C' WHEN 4 THEN 'D'
                         WHEN 5 THEN 'E' WHEN 6 THEN 'F' ELSE 'G' END,
       o.text,
       o.sort_order
FROM listening_options o
JOIN questions nq ON nq.legacy_id = o.question_id
JOIN question_groups g ON g.id = nq.group_id AND g.owner_type = 'LISTENING_TRACK';

ALTER TABLE questions DROP COLUMN legacy_id;
DROP TABLE reading_options;
DROP TABLE reading_questions;
DROP TABLE listening_options;
DROP TABLE listening_questions;

-- 5. Writing ------------------------------------------------------------------

CREATE TABLE writing_prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module VARCHAR(20) NOT NULL,
  task VARCHAR(10) NOT NULL,
  task_kind VARCHAR(40) NOT NULL,
  title VARCHAR(255) NOT NULL,
  prompt VARCHAR NOT NULL,
  -- Dữ liệu biểu đồ Task 1 dạng JSON, frontend tự vẽ. NULL với bài viết thư hoặc Task 2.
  chart_data VARCHAR,
  image_url VARCHAR(500),
  min_words INTEGER NOT NULL,
  topic VARCHAR(255),
  sample_answer VARCHAR,
  sample_band DOUBLE PRECISION,
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE writing_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  prompt_id BIGINT NOT NULL,
  attempt_id BIGINT,
  text VARCHAR NOT NULL,
  word_count INTEGER NOT NULL,
  time_spent_sec INTEGER,
  status VARCHAR(20) NOT NULL,
  score_ta DOUBLE PRECISION,
  score_cc DOUBLE PRECISION,
  score_lr DOUBLE PRECISION,
  score_gra DOUBLE PRECISION,
  band DOUBLE PRECISION,
  feedback VARCHAR,
  error VARCHAR,
  grader VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE,
  graded_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_writing_submissions_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_writing_submissions_prompt FOREIGN KEY (prompt_id) REFERENCES writing_prompts (id)
);
CREATE INDEX ix_writing_submissions_user ON writing_submissions (user_id, created_at);

-- 6. Speaking -----------------------------------------------------------------

CREATE TABLE speaking_prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part INTEGER NOT NULL,
  topic VARCHAR(255) NOT NULL,
  question VARCHAR NOT NULL,
  -- Part 2: các gạch đầu dòng "You should say", mảng JSON.
  cue_card_points VARCHAR,
  sort_order INTEGER NOT NULL
);

CREATE TABLE speaking_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  prompt_id BIGINT NOT NULL,
  audio_path VARCHAR(500),
  transcript VARCHAR,
  duration_sec INTEGER,
  status VARCHAR(20) NOT NULL,
  score_fc DOUBLE PRECISION,
  score_lr DOUBLE PRECISION,
  score_gra DOUBLE PRECISION,
  score_p DOUBLE PRECISION,
  band DOUBLE PRECISION,
  feedback VARCHAR,
  error VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE,
  graded_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_speaking_submissions_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_speaking_submissions_prompt FOREIGN KEY (prompt_id) REFERENCES speaking_prompts (id)
);
CREATE INDEX ix_speaking_submissions_user ON speaking_submissions (user_id, created_at);

-- 7. Bài thi: placement, mock, luyện một phần ---------------------------------------

CREATE TABLE ielts_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind VARCHAR(20) NOT NULL,
  module VARCHAR(20) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR,
  duration_min INTEGER NOT NULL,
  published BOOLEAN NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE test_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id BIGINT NOT NULL,
  skill VARCHAR(20) NOT NULL,
  ref_type VARCHAR(30) NOT NULL,
  ref_id BIGINT NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_test_sections_test FOREIGN KEY (test_id) REFERENCES ielts_tests (id)
);

CREATE TABLE test_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  test_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  submitted_at TIMESTAMP WITH TIME ZONE,
  -- Bản nháp Writing trong lúc thi: JSON {promptId: text}.
  writing_drafts VARCHAR,
  raw_listening INTEGER,
  total_listening INTEGER,
  raw_reading INTEGER,
  total_reading INTEGER,
  band_listening DOUBLE PRECISION,
  band_reading DOUBLE PRECISION,
  band_writing DOUBLE PRECISION,
  band_speaking DOUBLE PRECISION,
  band_overall DOUBLE PRECISION,
  CONSTRAINT fk_test_attempts_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_test_attempts_test FOREIGN KEY (test_id) REFERENCES ielts_tests (id)
);
CREATE INDEX ix_test_attempts_user ON test_attempts (user_id, started_at);

CREATE TABLE attempt_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id BIGINT NOT NULL,
  question_id BIGINT NOT NULL,
  given VARCHAR,
  points INTEGER,
  CONSTRAINT fk_attempt_answers_attempt FOREIGN KEY (attempt_id) REFERENCES test_attempts (id),
  CONSTRAINT fk_attempt_answers_question FOREIGN KEY (question_id) REFERENCES questions (id),
  CONSTRAINT uk_attempt_answers UNIQUE (attempt_id, question_id)
);

ALTER TABLE writing_submissions ADD CONSTRAINT fk_writing_submissions_attempt
  FOREIGN KEY (attempt_id) REFERENCES test_attempts (id);

-- 8. Lộ trình -------------------------------------------------------------------

CREATE TABLE roadmaps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  exam_date DATE,
  start_band DOUBLE PRECISION,
  target_band DOUBLE PRECISION NOT NULL,
  feasibility VARCHAR(20) NOT NULL,
  version INTEGER NOT NULL,
  generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_roadmaps_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_roadmaps_user_status ON roadmaps (user_id, status);

CREATE TABLE roadmap_phases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id BIGINT NOT NULL,
  kind VARCHAR(30) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  goal VARCHAR NOT NULL,
  sort_order INTEGER NOT NULL,
  CONSTRAINT fk_roadmap_phases_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmaps (id)
);

CREATE TABLE roadmap_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id BIGINT NOT NULL,
  phase_id BIGINT NOT NULL,
  due_date DATE NOT NULL,
  type VARCHAR(30) NOT NULL,
  skill VARCHAR(20),
  ref_type VARCHAR(30),
  ref_id BIGINT,
  title VARCHAR(255) NOT NULL,
  estimated_min INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_roadmap_tasks_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmaps (id),
  CONSTRAINT fk_roadmap_tasks_phase FOREIGN KEY (phase_id) REFERENCES roadmap_phases (id)
);
CREATE INDEX ix_roadmap_tasks_roadmap_due ON roadmap_tasks (roadmap_id, due_date);
